### ISSUE TITLE
is this project effectively dead?

### ISSUE THREAD

**Issue by kFuQ** [pysdr/pysdr#2]
pyqt5 will only support a max python version of 3.6 which was EOL 23DEC2021 and is going to be removed.  I don't see how this will continue to work without a lot of manual work.

![image0](https://user-images.githubusercontent.com/88947890/152648866-726c0b2f-c214-4b85-b3a7-bcc11b763c28.jpeg)

**Comment by 777arc** [comment]
It was never alive!!! 😢

**Comment by kFuQ** [comment]
if a lot of this was re-written in something like javascript, it wouldn't be too difficult to integrate into all kinds of things.

I found some js that would work for some of it, i just don't know how to put it together with rtl-sdr. #notaprogrammer

**Comment by 777arc** [comment]
I wouldn't worry about it, there's likely a different active and better project for whatever you are looking to do (what lead you to finding pysdr btw?).   Also feel free to check out https://pysdr.org/ =)

**Comment by kFuQ** [comment]
friend is working on a rpi4 project and i noticed so many of these websdr's are super old.  idea was to maybe make a newer one and wrap into react/vue/whatever.  with all the newer web tech now, i think it could probably be done in javascript making it a lot faster, more efficient and portable across devices, hardware and platforms.

i found some js (http://arc.id.au) that works well displaying spectrographs/waterfalls/etc and i know (technically) it ***shouldnt*** be too terribly difficult to write js functions to control the hardware over tcp/udp.  

if the base of it worked in react (for example) its not that big of a leap to add libraries to build your own home brew (mobile and desktop) apps for it as well as a web based app that could be hosted or ran locally using nodejs.

i just don't know enough about programming like that to make the buttons tell the device to make cool colored lines in the box and noise out the audio device.
