### ISSUE TITLE
X-axis labels are illegible on https://pysdr.org/_images/pulse_train.png 

### ISSUE THREAD

**Issue by warnes** [pysdr/pysdr#3]
The black text on top of the blue lines is almost invisible in the ISI plot in 13. Plot Shaping:

![](https://pysdr.org/_images/pulse_train.png)

The labels could be made clear by shifting their y-position downward, or by changing the color of either the lines (e.g. to cyan instead of blue) or the text (e.g. red instead of black.)

**Comment by 777arc** [comment]
Great suggestion, I through this together - https://pysdr.org/_images/pulse_train.svg

**Comment by warnes** [comment]
Much better!
